// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./error_kind";

export type AppError = { kind: ErrorKind, message: string, details: string | null, };
