// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlameLine = { line_number: number, commit_hash: string, author_name: string, author_time: bigint, summary: string, content: string, };
