// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./commit";
import type { CommitFile } from "./commit_file";

export type CommitDetails = { commit: Commit, files: Array<CommitFile>, };
