// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitFile = { path: string, status: string, old_path: string | null, additions: number | null, deletions: number | null, };
