// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConflictBlock = { id: number, base: string | null, ours: string, theirs: string, start_line: number, end_line: number, is_identical: boolean, };
