// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "Conflict" | "DirtyWorkingTree" | "AuthFailed" | "NotARepo" | "LockFile" | "NetworkUnavailable" | "GitNotFound" | "GitVersionTooOld" | "InvalidPath" | "Io" | "Unknown";
