// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitInfo = { available: boolean, version: string | null, path: string | null, is_valid_version: boolean, error: string | null, };
