// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictBlock } from "./conflict_block";

export type ParsedConflictFile = { path: string, has_markers: boolean, crlf: boolean, blocks: Array<ConflictBlock>, clean_text_suggestion: string, };
