// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefKind } from "./ref_kind";

export type RefChip = { name: string, kind: RefKind, };
