// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRef } from "./git_ref";

export type RepoRefs = { local_branches: Array<GitRef>, remote_branches: Array<GitRef>, tags: Array<GitRef>, current_branch: string | null, };
