// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StashItem = { index: number, selector: string, message: string, date: bigint, commit_hash: string, };
